//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asiakasrekisteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakasluokittelu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asiakasluokittelu()
        {
            this.Asiakastiedot = new HashSet<Asiakastiedot>();
        }
    
        public int LuokitteluID { get; set; }
        public string Toimiala { get; set; }
        public string Liitto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiakastiedot> Asiakastiedot { get; set; }
    }
}
