//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asiakasrekisteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakastiedot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asiakastiedot()
        {
            this.Laskutusosoite = new HashSet<Asiakastapahtumat>();
            this.Asiakastapahtumat = new HashSet<Asiakastapahtumat>();
            this.Laskutusosoite1 = new HashSet<Laskutusosoite>();
        }
    
        public int Asiakasnumero { get; set; }
        public string Nimi { get; set; }
        public string Yhteyshenkilö { get; set; }
        public Nullable<int> LuokitteluID { get; set; }
        public string Ytunnus { get; set; }
        public string Osoite { get; set; }
        public Nullable<int> PaikkakuntaID { get; set; }
        public string Postinumero { get; set; }
        public string Postitoimipaikka { get; set; }
        public string Puhelin { get; set; }
        public string Sähköposti { get; set; }
        public bool EriLaskutusosoite { get; set; }
    
        public virtual Asiakasluokittelu Asiakasluokittelu { get; set; }
        public virtual Postitoimipaikat Postitoimipaikat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiakastapahtumat> Laskutusosoite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiakastapahtumat> Asiakastapahtumat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Laskutusosoite> Laskutusosoite1 { get; set; }
    }
}
