//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asiakasrekisteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laskutusosoite
    {
        public int LaskutustietoID { get; set; }
        public Nullable<int> Asiakasnumero { get; set; }
        public string Nimi { get; set; }
        public string Ytunnus { get; set; }
        public string Osoite { get; set; }
        public string Postinumero { get; set; }
        public string Postitoimipaikka { get; set; }
        public string Sähköposti { get; set; }
    
        public virtual Asiakastiedot Asiakastiedot { get; set; }
    }
}
